version: 2.1
orbs:
  python: circleci/python@1.0.0

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
  build-and-push:
    executor: python/default
    steps:
      - checkout

workflows:

  backend:
    jobs:
      - test
      - build-and-push:
          filters:
            branches:
              only:
                - main
